name: Prison
version: '0.1-SNAPSHOT'
main: ksu.minecraft.prison.Prison
api-version: '1.21'
description: A simple plugin that responds with "Go Owls!" when /ksu is typed.
commands:
  ksu:
    description: Sends a custom message to the player.
    usage: /ksu
  prison:
    description: Main command for the Prison plugin.
    usage: /prison <args>
    aliases: [ prison ]
    # Define the subcommands, including 'help', 'ranks', and 'reload'
    subcommands:
      help:
        description: Opens the help menu.
        usage: /prison help
      ranks:
        description: Opens the ranks menu.
        usage: /prison ranks
      reload:
        description: Reloads the Prison plugin.
        usage: /prison reload
  ranks:
    description: Shows rank progression and costs.
    usage: /ranks
  rankup:
      description: Ranks up the player if they can afford it.
      usage: /rankup

permissions:
  prison.use:
    description: Allows a player to use the /prison command.
    default: true
  prison.admin:
    description: Allows a player to use admin commands for the plugin.
    default: op
permission-message: You do not have permission to execute this command.
depend: [LuckPerms, Vault]
